package com.skr.back;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RestController;

import com.skr.back.User;
import com.skr.back.UserRepository;

@CrossOrigin
@Controller    // This means that this class is a Controller
@RequestMapping(path="/login") // This means URL's start with /demo (after Application path)
public class UserController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@GetMapping(path="/signup") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String name
			, @RequestParam String password
			, @RequestParam Integer identity) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setName(name);
		n.setPassword(password);
		n.setIdentity(identity);
		userRepository.save(n);
		return "Saved";
	}

	// @GetMapping(path="/all")
	// public @ResponseBody Iterable<User> getAllUsers() {
	// 	// This returns a JSON or XML with the users
	// 	return userRepository.findAll();
	// }
	
	@GetMapping(path="/validate")
	public @ResponseBody User validate(@RequestParam String name){
		if(userRepository.existsById(name)){
			return userRepository.findById(name).get();
		}else{
			return new User();
		}
	}

	@GetMapping(path="/")
	public @ResponseBody String hello(){
		return "hello world";
	}
}